# Generated by Django 5.1.4 on 2026-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
