# Generated by Django 5.1.4 on 2026-07-08 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_cover_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeAccompaniment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_accompaniments', to=settings.AUTH_USER_MODEL)),
                ('from_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accompaniments_from', to='recipes.recipe')),
                ('to_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accompaniments_to', to='recipes.recipe')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('from_recipe', models.F('to_recipe')), _negated=True), name='accompaniment_no_self_link')],
                'unique_together': {('from_recipe', 'to_recipe')},
            },
        ),
    ]
