# Generated by Django 5.1.4 on 2026-07-31 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeaccompaniment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='recipes.recipe'),
        ),
    ]
