# Generated by Django 5.1.4 on 2026-08-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_collectionrecipe_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_event_fulfillment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
