# Generated by Django 5.1.4 on 2026-07-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shopping_staleness_days',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
