# Generated by Django 5.1.4 on 2026-07-08 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdish',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventdish',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_dishes', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='eventdishfulfillment',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='events.eventdish'),
        ),
        migrations.AddField(
            model_name='eventingredient',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='events.eventdish'),
        ),
        migrations.AddField(
            model_name='eventingredient',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventingredient',
            name='fulfillment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='events.eventdishfulfillment'),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventingredient',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_ingredients', to='events.eventparticipant'),
        ),
        migrations.AddField(
            model_name='eventdishfulfillment',
            name='fulfilled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='events.eventparticipant'),
        ),
        migrations.AddField(
            model_name='eventdish',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_dishes', to='events.eventparticipant'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='unique_user_per_event'),
        ),
        migrations.AddConstraint(
            model_name='eventingredient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dish__isnull', False), ('fulfillment__isnull', True)), models.Q(('dish__isnull', True), ('fulfillment__isnull', False)), _connector='OR'), name='event_ingredient_exactly_one_parent'),
        ),
    ]
