# Generated by Django 5.1.4 on 2026-07-08 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0004_recipeaccompaniment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('shopping', 'Shopping'), ('shopped', 'Shopped'), ('cooked', 'Cooked')], default='planned', max_length=20)),
                ('is_template', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('shopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['planned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_logs', to=settings.AUTH_USER_MODEL)),
                ('planned_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooking_logs', to='planner.plannedmeal')),
            ],
            options={
                'ordering': ['-cooked_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('planned_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='planner.plannedmeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['planned_meal', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedMealRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('target_servings', models.PositiveIntegerField(blank=True, null=True)),
                ('planned_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_recipes', to='planner.plannedmeal')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_appearances', to='recipes.recipe')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('planned_meal', 'recipe')},
            },
        ),
    ]
